name: hprofile-actions

on: 
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  Testing:
    runs-on: [self-hosted, master-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Maven Tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
